allowBuilds:
  '@scarf/scarf': true
  bcrypt: true
  esbuild: true
  msgpackr-extract: true
  unrs-resolver: true

onlyBuiltDependencies:
  - '@scarf/scarf'
  - bcrypt
  - esbuild
  - msgpackr-extract
  - unrs-resolver
